[package]
name = "redesmyn_storage"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
redesmyn_ids = { workspace = true, features = ["sqlx"] }
redesmyn_logging.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["macros", "migrate", "sqlite", "runtime-tokio"] }
tempfile.workspace = true
thiserror.workspace = true
time.workspace = true
ulid.workspace = true

[dev-dependencies]
prost.workspace = true
redesmyn_protocol.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
