[package]
name = "redesmyn_storage"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
redesmyn_ids = { workspace = true, features = ["sqlx"] }
redesmyn_logging.workspace = true
sqlx = { workspace = true, features = ["macros", "migrate", "sqlite", "runtime-tokio"] }
thiserror.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
