[package]
name = "redesmyn_ui"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
gpui.workspace = true
redesmyn_config.workspace = true
redesmyn_markdown.workspace = true
redesmyn_logging.workspace = true
redesmyn_protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
unicode-segmentation.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
gpui = { workspace = true, features = ["wayland", "x11"] }
