version = "Two"
fn_single_line = false
attr_fn_like_width = 80
struct_lit_width = 40
use_field_init_shorthand = true
match_block_trailing_comma = false
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
use_small_heuristics = "Max"
