[package]
name = "redesmyn_git"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
redesmyn_logging.workspace = true
redesmyn_protocol.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util", "process", "sync", "time"] }

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "test-util", "time"] }
