DEFAULT_AGENT_PRELUDE_TEMPLATE = (
    "Redesmyn agent prelude\n"
    "\n"
    "- Assigned task: {task_id} — {task_title}\n"
    "- Task doc: {task_doc}\n"
    "- Epic: {epic_slug} (read {epic_readme})\n"
    "- Branch: {branch}\n"
    "- Worktree: {worktree}\n"
    "\n"
    "Guidelines\n"
    "\n"
    "- Read AGENTS.md at repo root and follow it.\n"
    "- Prefer small, focused commits; keep changes maintainable and well-typed.\n"
    "- Start by understanding the task design + surrounding code; avoid unrelated changes.\n"
    "\n"
    "Tips\n"
    "\n"
    "- Run `just check` before you finish.\n"
    "- If you attach to this tmux session, detach with Ctrl-b then d (not Ctrl-c).\n"
)
