DEFAULT_AGENT_PRELUDE_TEMPLATE = (
    "Redesmyn agent prelude\n"
    "\n"
    "Assignment\n"
    "\n"
    "- You are assigned task {task_id}: {task_title}.\n"
    "- Read the task doc at {task_doc} and implement its requirements.\n"
    "\n"
    "Objective\n"
    "\n"
    "- Complete the task end-to-end: implement, validate, and leave the branch in a clean state.\n"
    "\n"
    "Context\n"
    "\n"
    "- Epic: {epic_slug} (read {epic_readme})\n"
    "- Branch: {branch}\n"
    "- Worktree: {worktree}\n"
    "\n"
    "Process\n"
    "\n"
    "- Read AGENTS.md at repo root and follow it.\n"
    "- Read the epic README and the task README before coding.\n"
    "- Keep changes small, well-typed, and easy to review; avoid unrelated changes.\n"
    "- If requirements or context are unclear, ask before making big assumptions.\n"
    "\n"
    "Requirements\n"
    "\n"
    "- Run `just check` before you finish.\n"
)
