[package]
name = "redesmyn_config"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
config = "0.14.1"
dotenvy = "0.15.7"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "2.0.11"

[dev-dependencies]
tempfile = "3.10.1"
