[package]
name = "redesmyn_protocol"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
redesmyn_ids.workspace = true
redesmyn_errors.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
