[package]
name = "redesmyn-daemon"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
redesmyn_config = { path = "../redesmyn_config" }
redesmyn_daemon = { path = "../redesmyn_daemon" }
redesmyn_logging = { path = "../redesmyn_logging" }

