[package]
name = "rn"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false
autobins = false
default-run = "rn-rs"

[[bin]]
name = "rn-rs"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

redesmyn_logging.workspace = true
redesmyn_protocol.workspace = true
