/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/healthz": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Healthz */
    get: operations["healthz_v1_healthz_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/v1/status": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Api Status */
    get: operations["api_status_v1_status_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AckReleaseResponse */
    AckReleaseResponse: {
      /** Requiredagentids */
      requiredAgentIds: number[]
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "acks"
    }
    /** ApiStatusResponse */
    ApiStatusResponse: {
      block: components["schemas"]["BlockStatusResponse"] | null
      /** Dbpath */
      dbPath: string
      /** Defaultbranch */
      defaultBranch: string | null
      /** Reporoot */
      repoRoot: string
    }
    /**
     * BlockMode
     * @enum {string}
     */
    BlockMode: "lax" | "strict"
    /**
     * BlockPolicy
     * @enum {string}
     */
    BlockPolicy: "git_mutations" | "daemon_mutations"
    /** BlockScopeResponse */
    BlockScopeResponse: {
      /** Frombranch */
      fromBranch: string | null
      /** Repo */
      repo: boolean
      /** Tobranch */
      toBranch: string | null
    }
    /** BlockStatusResponse */
    BlockStatusResponse: {
      mode: components["schemas"]["BlockMode"]
      policy: components["schemas"]["BlockPolicy"]
      /** Reason */
      reason: string | null
      /** Release */
      release: components["schemas"]["ManualReleaseResponse"] | components["schemas"]["CommandReleaseResponse"] | components["schemas"]["AckReleaseResponse"]
      scope: components["schemas"]["BlockScopeResponse"]
    }
    /** CommandReleaseResponse */
    CommandReleaseResponse: {
      /** Commandid */
      commandId: number
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "command"
    }
    /** ManualReleaseResponse */
    ManualReleaseResponse: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "manual"
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  healthz_v1_healthz_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: string
          }
        }
      }
    }
  }
  api_status_v1_status_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ApiStatusResponse"]
        }
      }
    }
  }
}
