/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/healthz": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Healthz */
    get: operations["healthz_v1_healthz_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/v1/status": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Api Status */
    get: operations["api_status_v1_status_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ApiStatusResponse */
    ApiStatusResponse: {
      /** Dbpath */
      dbPath: string
      /** Defaultbranch */
      defaultBranch: string | null
      pause: components["schemas"]["PauseStatusResponse"] | null
      /** Reporoot */
      repoRoot: string
    }
    /**
     * PauseMode
     * @enum {string}
     */
    PauseMode: "lax" | "strict"
    /** PauseScopeResponse */
    PauseScopeResponse: {
      /** Frombranch */
      fromBranch: string | null
      /** Repo */
      repo: boolean
      /** Tobranch */
      toBranch: string | null
    }
    /** PauseStatusResponse */
    PauseStatusResponse: {
      mode: components["schemas"]["PauseMode"]
      /** Reason */
      reason: string | null
      scope: components["schemas"]["PauseScopeResponse"]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  healthz_v1_healthz_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: string
          }
        }
      }
    }
  }
  api_status_v1_status_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ApiStatusResponse"]
        }
      }
    }
  }
}
