"""db baseline

Revision ID: 0001_baseline
Revises:
Create Date: 2025-12-30 19:54:40.187581
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_repo", sa.Boolean(), nullable=False),
        sa.Column("scope_from_branch", sa.String(), nullable=True),
        sa.Column("scope_to_branch", sa.String(), nullable=True),
        sa.Column(
            "policy",
            sa.Enum(
                "git_mutations",
                "daemon_mutations",
                name="block_policy",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum("lax", "strict", name="block_mode", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "release",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cleared_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "harness_profiles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "builtin", "user", name="harness_profile_source", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column(
            "definition",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hosts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("host_key", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column(
            "capabilities",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_key"),
    )
    op.create_table(
        "linear_auth",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("token_type", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("epic_id", sa.Integer(), nullable=False),
        sa.Column("branch_name", sa.String(), nullable=False),
        sa.Column("parent_node_id", sa.Integer(), nullable=True),
        sa.Column("agent_id", sa.Integer(), nullable=True),
        sa.Column("worktree_path", sa.String(), nullable=True),
        sa.Column("primary_task_id", sa.Integer(), nullable=True),
        sa.Column("github_pr_id", sa.String(), nullable=True),
        sa.Column("linear_issue_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["epic_id"],
            ["epics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_node_id"],
            ["nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["primary_task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("epic_id", "branch_name", name="uq_nodes_epic_branch"),
    )
    op.create_index(op.f("ix_nodes_agent_id"), "nodes", ["agent_id"], unique=False)
    op.create_index(op.f("ix_nodes_epic_id"), "nodes", ["epic_id"], unique=False)
    op.create_index(
        op.f("ix_nodes_parent_node_id"), "nodes", ["parent_node_id"], unique=False
    )
    op.create_index(
        op.f("ix_nodes_primary_task_id"), "nodes", ["primary_task_id"], unique=False
    )
    op.create_table(
        "repositories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repo_root", sa.String(), nullable=False),
        sa.Column("default_branch", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_root"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("epic_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("local", "linear", "github", name="task_source", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "authority",
            sa.Enum(
                "local", "linear", "github", name="task_authority", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "todo",
                "in_progress",
                "blocked",
                "done",
                name="task_state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("node_id", sa.Integer(), nullable=True),
        sa.Column("linear_issue_id", sa.String(), nullable=True),
        sa.Column("github_issue_id", sa.String(), nullable=True),
        sa.Column("local_path", sa.String(), nullable=True),
        sa.Column("merge_ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["epic_id"],
            ["epics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_epic_id"), "tasks", ["epic_id"], unique=False)
    op.create_index(op.f("ix_tasks_node_id"), "tasks", ["node_id"], unique=False)
    op.create_table(
        "agents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "stopped",
                "running",
                "blocked",
                "error",
                name="agent_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("host_id", sa.Integer(), nullable=True),
        sa.Column("harness_profile_id", sa.String(), nullable=True),
        sa.Column("cwd_path", sa.String(), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column(
            "attach",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "resolved_profile",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["harness_profile_id"],
            ["harness_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["hosts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agents_harness_profile_id"),
        "agents",
        ["harness_profile_id"],
        unique=False,
    )
    op.create_index(op.f("ix_agents_host_id"), "agents", ["host_id"], unique=False)
    op.create_table(
        "epics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("root_branch", sa.String(), nullable=False),
        sa.Column("linear_project_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "slug", name="uq_epics_repo_slug"),
    )
    op.create_index(
        op.f("ix_epics_repository_id"), "epics", ["repository_id"], unique=False
    )
    op.create_table(
        "block_acks",
        sa.Column("block_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column(
            "acked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["blocks.id"],
        ),
        sa.PrimaryKeyConstraint("block_id", "agent_id"),
    )
    op.create_table(
        "commands",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("command_type", sa.String(), nullable=False),
        sa.Column("target_agent_id", sa.Integer(), nullable=True),
        sa.Column("target_node_id", sa.Integer(), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "canceled",
                name="command_state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["target_agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_node_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_commands_target_agent_id"),
        "commands",
        ["target_agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_commands_target_node_id"), "commands", ["target_node_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_commands_target_node_id"), table_name="commands")
    op.drop_index(op.f("ix_commands_target_agent_id"), table_name="commands")
    op.drop_table("commands")
    op.drop_table("block_acks")
    op.drop_index(op.f("ix_epics_repository_id"), table_name="epics")
    op.drop_table("epics")
    op.drop_index(op.f("ix_agents_host_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_harness_profile_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_tasks_node_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_epic_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("repositories")
    op.drop_index(op.f("ix_nodes_primary_task_id"), table_name="nodes")
    op.drop_index(op.f("ix_nodes_parent_node_id"), table_name="nodes")
    op.drop_index(op.f("ix_nodes_epic_id"), table_name="nodes")
    op.drop_index(op.f("ix_nodes_agent_id"), table_name="nodes")
    op.drop_table("nodes")
    op.drop_table("linear_auth")
    op.drop_table("hosts")
    op.drop_table("harness_profiles")
    op.drop_table("events")
    op.drop_table("blocks")
    # ### end Alembic commands ###
