[package]
name = "redesmyn_control_plane"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
redesmyn_config.workspace = true
redesmyn_domain.workspace = true
redesmyn_ids.workspace = true
redesmyn_logging.workspace = true
redesmyn_protocol.workspace = true
redesmyn_storage.workspace = true
redesmyn_transport.workspace = true
thiserror.workspace = true
