name: GitHub Pages

on:
  push:
    branches: ["dg/gh-pages"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: python3 -m pip install -U pipenv && make install-py

      - name: Build Python package
        uses: PyO3/maturin-action@v1
        with:
          command: develop
          container: 'off'
          rust-toolchain: nightly
          args: '--target-dir dist --pip-path "$(pipenv --venv)/bin/pip3" -m py-redesmyn/Cargo.toml'
          sccache: 'true'

      - name: Generate documentation
        run: make docs-py

      - name: Configure pages
        uses: actions/configure-pages@v5

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: py-redesmyn/docs/build/html

      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v4
